announces_controllers:
    prefix: /api/announces
    resource:
        path: ../src/Announce/Controller
        namespace: App\Announce\Controller
    type: attribute
    trailing_slash_on_root: false
