# Development environment override
services:
    php:
        container_name: event-manager-php
        build:
            context: .
            target: frankenphp_dev
        #ports:
        #   - "11115:11115" Uncomment this line if you use PHPStan PRO or remove
        volumes:
            - ./:/app
            - ../.castor:/.castor
            - ~/.ssh:/home/www-data/.ssh:ro
            - user_data:/home/www-data
            - ./.docker/php/Caddyfile.dev:/etc/caddy/Caddyfile:ro
            - ./.docker/php/conf.d/dev/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
            # If you develop on Mac or Windows you can remove the vendor/ directory
            #  from the bind-mount for better performance by enabling the next line:
            #- /app/vendor
        environment:
            MERCURE_EXTRA_DIRECTIVES: demo
            # See https://xdebug.org/docs/all_settings#mode
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"
            SYMFONY_VERSION: "7.3.*-dev"
        extra_hosts:
            # Ensure that host.docker.internal is correctly defined on Linux
            - host.docker.internal:host-gateway
        tty: true
        labels:
            - "traefik.enable=true"
            - "traefik.network=traefik"
            - "traefik.http.routers.php-event-manager.rule=Host(`event-manager.api.localhost`)"
            - "traefik.http.routers.php-event-manager.tls=true"
            - "traefik.http.services.php-event-manager.loadbalancer.server.port=80"
            - "traefik.http.routers.php-event-manager.middlewares=php-event-manager-cors"

            # CORS and Forward Headers Middleware
            - "traefik.http.middlewares.php-event-manager-cors.headers.accesscontrolallowmethods=GET,POST,PUT,PATCH,DELETE,OPTIONS"
            - "traefik.http.middlewares.php-event-manager-cors.headers.accesscontrolallowheaders=*"
            - "traefik.http.middlewares.php-event-manager-cors.headers.accesscontrolalloworiginlist=*"
            #      - "traefik.http.middlewares.php-event-manager-cors.headers.accesscontrolmaxage=100"
            #      - "traefik.http.middlewares.php-event-manager-cors.headers.addvaryheader=true"

            # Forward Headers from Traefik to Caddy
        #      - "traefik.http.middlewares.php-event-manager-cors.headers.customrequestheaders.X-Forwarded-Proto=https"
        #      - "traefik.http.middlewares.php-event-manager-cors.headers.customrequestheaders.X-Forwarded-Host={{PLACEHOLDER}}..bruno.localhost"
        #      - "traefik.http.middlewares.php-event-manager-cors.headers.customrequestheaders.X-Real-IP={client_ip}"
        networks:
            - traefik

    ###> symfony/mercure-bundle ###
    ###< symfony/mercure-bundle ###

    ###> doctrine/doctrine-bundle ###
    database:
        container_name: event-manager-database
    ###< doctrine/doctrine-bundle ###

    pgbouncer: # permit multiple connections to the database
        image: edoburu/pgbouncer:latest
        container_name: event-manager-pgbouncer
        environment:
            DATABASE_URL: postgres://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD:-root}@database/${POSTGRES_DB:-app}
        volumes:
            - ./.docker/pgbouncer:/etc/pgbouncer
        ports:
            - "6435:6432"
        depends_on:
            - database
        networks:
            - database

networks:
    traefik:
        external: true

volumes:
    user_data:
