# Development environment override
services:
    front:
        container_name: event-manager-front
        build:
            target: dev
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.front-event-manager.rule=Host(`event-manager.web.localhost`)"
            - "traefik.http.routers.front-event-manager.tls=true"
            - "traefik.http.services.front-event-manager.loadbalancer.server.port=5173"
            - "traefik.http.routers.front-event-manager.service=front-event-manager"
            - "traefik.http.routers.front-event-manager-devtools.rule=Host(`event-manager-front-devtools.web.localhost`)"
            - "traefik.http.routers.front-event-manager-devtools.tls=true"
            - "traefik.http.services.front-event-manager-devtools.loadbalancer.server.port=5001"
            - "traefik.http.routers.front-event-manager-devtools.service=front-event-manager-devtools"
        networks:
            - traefik

networks:
    traefik:
        external: true
