# Development environment override
services:
    front:
        container_name: anonciator-front
        build:
            target: dev
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.front-anonciator.rule=Host(`anonciator.web.localhost`)"
            - "traefik.http.routers.front-anonciator.tls=true"
            - "traefik.http.services.front-anonciator.loadbalancer.server.port=5173"
            - "traefik.http.routers.front-anonciator.service=front-anonciator"
            - "traefik.http.routers.front-anonciator-devtools.rule=Host(`anonciator-front-devtools.web.localhost`)"
            - "traefik.http.routers.front-anonciator-devtools.tls=true"
            - "traefik.http.services.front-anonciator-devtools.loadbalancer.server.port=5001"
            - "traefik.http.routers.front-anonciator-devtools.service=front-anonciator-devtools"
        networks:
            - traefik

networks:
    traefik:
        external: true
