# Development environment override
services:
    front:
        container_name: {{PREFIX_CONTAINER}}-front
        build:
            target: dev
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.front-{{PREFIX_CONTAINER}}.rule=Host(`{{PREFIX_URL}}.web.localhost`)"
            - "traefik.http.routers.front-{{PREFIX_CONTAINER}}.tls=true"
            - "traefik.http.services.front-{{PREFIX_CONTAINER}}.loadbalancer.server.port=5173"
            - "traefik.http.routers.front-{{PREFIX_CONTAINER}}.service=front-{{PREFIX_CONTAINER}}"
            - "traefik.http.routers.front-{{PREFIX_CONTAINER}}-devtools.rule=Host(`{{PREFIX_URL}}-front-devtools.web.localhost`)"
            - "traefik.http.routers.front-{{PREFIX_CONTAINER}}-devtools.tls=true"
            - "traefik.http.services.front-{{PREFIX_CONTAINER}}-devtools.loadbalancer.server.port=5001"
            - "traefik.http.routers.front-{{PREFIX_CONTAINER}}-devtools.service=front-{{PREFIX_CONTAINER}}-devtools"
        networks:
            - traefik

networks:
    traefik:
        external: true
